/**
 * operatoros init — scaffold a new workspace.
 *
 * Creates the standard layout and writes operatoros.yaml.
 * Default preset: personal.
 */
import * as fs from "fs-extra";
import * as path from "path";
import { heading, ok, info, fail } from "../lib/print";
import { WORKSPACE_FILENAME, WORKSPACE_LAYOUT } from "../lib/workspace";

interface InitOptions {
  personal?: boolean;
  preset?: string;
  target?: string;
  force?: boolean;
}

export async function initCommand(opts: InitOptions): Promise<void> {
  heading("OperatorOS init");

  const target = path.resolve(opts.target ?? process.cwd());
  const preset = opts.preset ?? (opts.personal ? "personal" : "personal");

  if (await fs.pathExists(path.join(target, WORKSPACE_FILENAME))) {
    if (!opts.force) {
      fail(`workspace already exists at ${target} (use --force to overwrite)`);
      process.exit(1);
    }
  }

  info(`target: ${target}`);
  info(`preset: ${preset}`);

  // Create layout
  for (const folder of WORKSPACE_LAYOUT) {
    await fs.ensureDir(path.join(target, folder));
  }
  ok(`created layout: ${WORKSPACE_LAYOUT.join(", ")}/`);

  // operatoros.yaml
  const manifest = renderManifest(preset);
  await fs.writeFile(path.join(target, WORKSPACE_FILENAME), manifest);
  ok(`created ${WORKSPACE_FILENAME}`);

  // presets/personal/preset.yaml
  const presetYaml = renderPreset();
  const presetDir = path.join(target, "presets", "personal");
  await fs.ensureDir(presetDir);
  await fs.writeFile(path.join(presetDir, "preset.yaml"), presetYaml);
  ok(`created presets/personal/preset.yaml`);

  // schemas/README pointer (the actual schemas live in repo, copied at init for self-containment)
  await fs.writeFile(
    path.join(target, "schemas", "README.md"),
    "# schemas/\n\nSchemas for this workspace are validated against the OperatorOS Core schemas shipped in the framework repo:\n\n- https://github.com/taras-polishchuk/operatoros-framework/tree/main/schemas\n\nRun `operatoros validate <path>` to check any workspace/module/preset against its schema.\n"
  );
  ok(`created schemas/README.md`);

  // state/README
  await fs.writeFile(
    path.join(target, "state", "README.md"),
    "# state/\n\nMutable runtime state for this workspace. Should be in `.gitignore`.\n"
  );
  ok(`created state/README.md`);

  // vault/README — secret storage
  await fs.writeFile(
    path.join(target, "vault", "README.md"),
    "# vault/\n\nEncrypted secrets storage. Never commit this directory.\n\nOperatorOS Core's `export` command will deny-list this folder by default.\n"
  );
  ok(`created vault/README.md`);

  // modules/README — empty until you `operatoros add`
  await fs.writeFile(
    path.join(target, "modules", "README.md"),
    "# modules/\n\nModules extend your workspace. Install one with:\n\n    operatoros add <path-or-url>\n\nModules declare their contract via `module.yaml` at the root.\n"
  );
  ok(`created modules/README.md`);

  console.log("\n  next: cd into your workspace and run:");
  console.log("    $ operatoros validate operatoros.yaml\n");
}

function renderManifest(preset: string): string {
  return `# operatoros.yaml — workspace manifest
# generated by operatoros-core v0.2.0-alpha
version: "0.2"
name: personal-workspace
preset: ${preset}
modules: []
created_at: "${new Date().toISOString()}"
operatoros_version: "0.2.0-alpha"
`;
}

function renderPreset(): string {
  return `# preset.yaml — canonical personal preset
version: "0.2"
name: personal
description: |
  Single-operator default. Skeleton workspace with no modules installed.
modules: []
settings:
  vault_path: vault/
  state_path: state/
  export:
    deny:
      - "vault/**"
      - "**/.env"
      - "**/*.sqlite"
      - "**/id_rsa*"
      - "**/secrets.yaml"
`;
}