#!/usr/bin/env node
/**
 * OperatorOS Core CLI — main entry point.
 *
 * Implements the OperatorOS framework spec defined in this repo's schemas/ directory.
 * CLI surface (7 commands):
 *   operatoros init [--preset <name>] [--target <path>] [--force]
 *   operatoros validate <path> [--schema <name>]
 *   operatoros add <module-path-or-url> [--name <name>] [--pin <ref>]
 *   operatoros apply [preset]
 *   operatoros run <module> <command> [args...]
 *   operatoros export [--bundle tar.gz] [--out <path>] [--include-secrets]
 *   operatoros version
 */
import { Command } from "commander";
import { installEmbeddedAssets } from "./embedded-assets";
installEmbeddedAssets(); // must run before any command reads globals
import { initCommand } from "./commands/init";
import { validateCommand } from "./commands/validate";
import { addCommand } from "./commands/add";
import { applyCommand } from "./commands/apply";
import { runCommand } from "./commands/run";
import { exportCommand } from "./commands/export";
import { versionCommand } from "./commands/version";

// __EMBEDDED_ASSETS__
// Auto-generated by scripts/embed-assets.js at ncc-build time. In dev mode
// (tsc + node dist/cli.js) this is a no-op — init.ts / schema.ts fall back
// to a filesystem walk-up search. Removing the stale inlined literal
// avoids shipping presets/schemas that diverge from the on-disk source.
// __EMBEDDED_ASSETS_END__




const program = new Command();

program
  .name("operatoros")
  .description("OperatorOS Core — CLI runtime for personal operating systems")
  .version("0.5.2-alpha");

program
  .command("init")
  .description("Initialize a new OperatorOS workspace")
  .option("-p, --personal", "scaffold a personal workspace (default preset)")
  .option("--preset <name>", "use a specific preset (e.g., personal, minimal, team-research, dev-machine)")
  .option("-t, --target <path>", "target directory (default: current dir)")
  .option("-f, --force", "overwrite existing files")
  .action(initCommand);

program
  .command("validate <path>")
  .description("Validate a workspace/module/preset against its JSON-Schema")
  .option("--schema <name>", "schema name (workspace, module, preset)")
  .action(validateCommand);

program
  .command("add <source>")
  .description("Install a module from a local path or git URL")
  .option("-n, --name <name>", "override module name")
  .option("--pin <ref>", "git ref (branch/tag/sha) when source is a git URL")
  .action(addCommand);

program
  .command("apply [preset]")
  .description("Apply a preset — install all modules declared in the preset's preset.yaml")
  .action(applyCommand);

program
  .command("run <module> <command> [args...]")
  .description("Execute a command from an installed module")
  .action(runCommand);

program
  .command("export")
  .description("Export the current workspace as a portable bundle")
  .option("-b, --bundle <format>", "bundle format (tar.gz, zip)", "tar.gz")
  .option("-o, --out <path>", "output file path")
  .option("--include-secrets", "include secret files (default: deny-list)")
  .action(exportCommand);

program
  .command("version")
  .description("Print OperatorOS Core version")
  .action(versionCommand);

program.parseAsync(process.argv).catch((err) => {
  console.error(`\n✗ ${err.message ?? err}`);
  process.exit(1);
});