#!/usr/bin/env node
/**
 * OperatorOS Core CLI — main entry point.
 *
 * Implements the OperatorOS framework spec defined in this repo's schemas/ directory.
 * CLI surface (14 commands — v0.8.0):
 *   operatoros init [--preset <name>] [--target <path>] [--force]
 *   operatoros validate <path> [--schema <name>]
 *   operatoros add <module-path-or-url> [--name <name>] [--pin <ref>]
 *   operatoros apply [preset]
 *   operatoros run <module> <command> [args...]
 *   operatoros export [--bundle <format>] [--out <path>] [--include-secrets]
 *   operatoros version
 *   -- v0.7.0: Workspace Catalog commands (catalog is a pure, durable artifact inventory)
 *   operatoros index                     # rebuild .operatoros/index.json
 *   operatoros doctor [--target <path>]  # report workspace health
 *   operatoros stats [--target <path>]   # report counts/sizes by type
 *   operatoros stale [--target <path>]   # list orphan artifacts
 *   operatoros prune [--paths ...] [--dry-run | --confirm]
 *   -- v0.8.0: Three-section workspace report
 *   operatoros inspect [--target <path>] [--format md|json|terminal] [--no-bootstrap]
 */
import { Command } from "commander";
import { installEmbeddedAssets } from "./embedded-assets";
installEmbeddedAssets(); // must run before any command reads globals
import { initCommand } from "./commands/init";
import { validateCommand } from "./commands/validate";
import { addCommand } from "./commands/add";
import { applyCommand } from "./commands/apply";
import { runCommand } from "./commands/run";
import { exportCommand } from "./commands/export";
import { versionCommand } from "./commands/version";
// v0.7.0 Workspace Catalog commands
import { indexCommand } from "./commands/index";
import { doctorCommand } from "./commands/doctor";
import { statsCommand } from "./commands/stats";
import { staleCommand } from "./commands/stale";
import { pruneCommand } from "./commands/prune";
// v0.8.0 — Three-section workspace report
import { inspectCommand } from "./commands/inspect";
import { version as pkgVersion } from "../package.json";

// __EMBEDDED_ASSETS__
// Auto-generated by scripts/embed-assets.js at ncc-build time. In dev mode
// (tsc + node dist/cli.js) this is a no-op — init.ts / schema.ts fall back
// to a filesystem walk-up search. Removing the stale inlined literal
// avoids shipping presets/schemas that diverge from the on-disk source.
// __EMBEDDED_ASSETS_END__



// Single source of truth for the CLI version: read from package.json at
// runtime so CHANGELOG / README / `operatoros version` stay synchronized.
// In ncc-bundled binaries this resolves to the bundled manifest; in dev mode
// it resolves from core/package.json via Node's resolver.
const CORE_VERSION = pkgVersion;

const program = new Command();

program
  .name("operatoros")
  .description("OperatorOS Core — CLI runtime for personal operating systems")
  .version(CORE_VERSION)
  .enablePositionalOptions()
  .showSuggestionAfterError(true);

program
  .command("init")
  .description("Initialize a new OperatorOS workspace")
  .option("-p, --personal", "scaffold a personal workspace (default preset)")
  .option("--preset <name>", "use a specific preset (e.g., personal, minimal, team-research, dev-machine)")
  .option("-t, --target <path>", "target directory (default: current dir)")
  .option("-f, --force", "overwrite existing files")
  .addHelpText("after", `
Examples:
  $ operatoros init --target my-os
  $ operatoros init --preset personal --target ~/projects/personal
  $ operatoros init --force                       # overwrite existing init`)
  .action(initCommand);

program
  .command("validate <path>")
  .description("Validate a workspace/module/preset against its JSON-Schema")
  .option("--schema <name>", "schema name (workspace, module, preset)")
  .addHelpText("after", `
Examples:
  $ operatoros validate operatoros.yaml
  $ operatoros validate ./modules/my-module --schema module
  $ operatoros validate ./presets/personal/preset.yaml --schema preset`)
  .action(validateCommand);

program
  .command("add <source>")
  .alias("install")
  .description("Install a module from a local path or git URL (alias: install)")
  .option("-n, --name <name>", "override module name")
  .option("--pin <ref>", "git ref (branch/tag/sha) when source is a git URL")
  .addHelpText("after", `
Examples:
  $ operatoros add ./modules/my-module
  $ operatoros install ./modules/my-module      # alias for "add"
  $ operatoros add https://github.com/me/my-module.git
  $ operatoros add https://github.com/me/my-module.git --pin v1.0.0
  $ operatoros add ./local-module --name custom-name`)
  .action(addCommand);

program
  .command("apply [preset]")
  .description("Apply a preset — install all modules declared in the preset's preset.yaml")
  .addHelpText("after", `
Examples:
  $ operatoros apply                    # apply the preset named in operatoros.yaml
  $ operatoros apply personal           # apply the 'personal' preset explicitly
  $ operatoros apply team-research`)
  .action(applyCommand);

program
  .command("run <module> <command> [args...]")
  .description("Execute a command from an installed module")
  .enablePositionalOptions()
  .passThroughOptions()
  .showSuggestionAfterError(true)
  .option("-t, --target <path>", "target workspace (default: walk-up from cwd)")
  .addHelpText("after", `
Examples:
  $ operatoros run context-builder inspect
  $ operatoros run drift-detector check --strict
  $ operatoros run my-module greet "Taras"
  $ operatoros run bootstrap-md render --target .

Module scripts receive WORKSPACE_ROOT and MODULE_DIR as env vars.
The --target flag and any extra args are passed through to the
underlying module command. Module scripts should accept their own
positional args; --target sets the workspace context for them.`)
  .action(runCommand);

program
  .command("export")
  .description("Export the current workspace as a portable bundle")
  .option("-b, --bundle <format>", "bundle format (tar.gz, zip)", "tar.gz")
  .option("-o, --out <path>", "output file path")
  .option("--include-secrets", "include secret files (default: deny-list)")
  .addHelpText("after", `
Examples:
  $ operatoros export                                  # writes ./operatoros-workspace.tar.gz
  $ operatoros export -o backup.tar.gz
  $ operatoros export --bundle zip -o workspace.zip
  $ operatoros export --include-secrets               # include vault/ (off by default)`)
  .action(exportCommand);

program
  .command("version")
  .description("Print OperatorOS Core version")
  .addHelpText("after", `
Examples:
  $ operatoros version
  Output: operatoros-core: 0.8.0, git: <branch> @ <sha>`)
  .action(versionCommand);

program
  .command("inspect")
  .description("Three-section workspace report (inventory / cold-read narrative / structural gaps). Non-destructive.")
  .option("-t, --target <path>", "target directory (default: workspace root or cwd)")
  .option("--format <fmt>", "output format: md (default) | json | terminal")
  .option("--no-bootstrap", "do not recommend or mention bootstrap.md")
  .addHelpText("after", `
Examples:
  $ operatoros inspect                              # report on the workspace you're in
  $ operatoros inspect --target /path/to/project    # any project, not just operatoros
  $ operatoros inspect --format json                 # machine-readable
  $ operatoros inspect --format terminal --no-bootstrap  # concise, no bootstrap.md mention

Use case: drop operatoros into any project to see what an AI
agent would "see cold" when entering. Works on non-OperatorOS
projects too — that's the aha moment.`)
  .action((opts) => {
    void inspectCommand(opts);
  });

program
  .command("index")
  .description("Rebuild the Workspace Catalog (.operatoros/index.json). Durable metadata only — no usage tracking or telemetry.")
  .option("-t, --target <path>", "target directory (default: workspace root or cwd)")
  .addHelpText("after", `
Examples:
  $ operatoros index                    # rebuild catalog for the current workspace
  $ operatoros index --target /path/to/workspace

The catalog contains ONLY durable metadata (path, type, size, mtime,
content_hash, indexed_at). No background processes; no telemetry.
The catalog is a pure inventory snapshot, refreshed on explicit
invocation only.`)
  .action((opts) => indexCommand(opts));

program
  .command("doctor")
  .description("Workspace diagnostics: report manifest validity, layout completeness, catalog freshness.")
  .option("-t, --target <path>", "target directory (default: workspace root or cwd)")
  .addHelpText("after", `
Examples:
  $ operatoros doctor                    # check the current workspace
  $ operatoros doctor --target /path/to/workspace

Reports findings by level (error / warning / info). Exits with
code 1 if any error-level finding is present. Run after a fresh
init to confirm the scaffold is well-formed.`)
  .action(async (opts) => {
    const result = await doctorCommand(opts);
    for (const f of result.findings) {
      console.log(`[${f.level}] ${f.code}: ${f.message}`);
    }
    if (!result.ok) process.exit(1);
  });

program
  .command("stats")
  .description("Workspace statistics: file counts, sizes, type breakdown. Reads catalog if present.")
  .option("-t, --target <path>", "target directory (default: workspace root or cwd)")
  .addHelpText("after", `
Examples:
  $ operatoros stats                    # count + size by type
  $ operatoros stats --target /path/to/workspace

Output: JSON with fileCount, directoryCount, symlinkCount, byType,
totalSize, catalogIndexedAt, catalogStale, scannedDirect.`)
  .action(async (opts) => {
    const s = await statsCommand(opts);
    console.log(JSON.stringify(s, null, 2));
  });

program
  .command("stale")
  .description("List orphan artifacts: files with no in-workspace references and not in denylist.")
  .option("-t, --target <path>", "target directory (default: workspace root or cwd)")
  .addHelpText("after", `
Examples:
  $ operatoros stale                    # list orphans in the current workspace
  $ operatoros stale --target /path/to/workspace

Outputs one path per line. "Orphan" = no in-workspace reference and
not in the denylist. Read-only — does not modify the workspace.`)
  .action(async (opts) => {
    const orphans = await staleCommand(opts);
    for (const o of orphans) console.log(o.path);
  });

program
  .command("prune")
  .description("Two-phase cleanup. Default: --dry-run lists planned deletions. Pass --paths <list> --confirm to delete.")
  .option("-t, --target <path>", "target directory (default: workspace root or cwd)")
  .option("--paths [paths...]", "explicit paths to delete (else derives from `stale`)")
  .option("--dry-run", "list planned deletions only (default when --confirm is absent)")
  .option("--confirm", "confirm deletion; requires --paths")
  .addHelpText("after", `
Examples:
  $ operatoros prune                              # dry-run; lists what would be deleted
  $ operatoros prune --paths foo.txt bar.md --confirm
  $ operatoros prune --target /path/to/workspace

WARNING: --confirm deletes files. The default is --dry-run which
prints planned deletions without touching the filesystem.

Destructive action — combine with --target to scope.
--dry-run is the default when --confirm is absent.
--dry-run + --confirm: --confirm wins (explicit destructive path).`)
  .action(async (opts) => {
    // Commander coerce: dryRun defaults to true UNLESS user passed --confirm.
    // - If user passed neither: dryRun=true (safe default).
    // - If user passed --confirm: dryRun=false (explicit destructive path).
    // - If user passed --dry-run + --confirm: dryRun=false (--confirm wins).
    const dryRun = opts.confirm ? false : opts.dryRun !== undefined ? opts.dryRun : true;
    const o = {
      target: opts.target,
      paths: opts.paths ?? [],
      dryRun,
      confirm: !!opts.confirm,
    };
    await pruneCommand(o);
  });

program.parseAsync(process.argv).catch((err) => {
  console.error(`\n✗ ${err.message ?? err}`);
  process.exit(1);
});