/**
 * catalog.test.ts — Workspace Catalog feature (v0.7.0 GATE: Workspace Catalog).
 *
 * Catalog is a durable metadata inventory of Workspace artifacts:
 *   .operatoros/index.json
 *
 * It is generated by `operatoros index` and consumed by read-only commands
 * (doctor, stats, stale, prune). Catalog schema is at schemas/catalog.schema.json.
 * Catalog contains ONLY durable metadata (per brief §6):
 *   - path (relative to workspace root)
 *   - type (file|directory|symlink)
 *   - size (bytes, 0 for directories)
 *   - mtime (ISO 8601 timestamp)
 *   - content_hash (SHA-256 hex, only for files; "" for directories/symlinks)
 *   - indexed_at (ISO 8601 timestamp when catalog was generated)
 *
 * Explicitly NOT in catalog (per brief §6):
 *   - opened_count
 *   - last_accessed_at
 *   - access timestamps
 *   - usage telemetry
 *
 * Tests follow TDD: RED → GREEN → REFACTOR. Each test verifies ONE behavior.
 */
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "fs-extra";
import * as path from "path";
import * as os from "os";
import * as crypto from "crypto";

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const SCHEMA_PATH = path.join(
  REPO_ROOT,
  "schemas",
  "catalog.schema.json"
);

describe("Workspace Catalog (v0.7.0 GATE: Workspace Catalog)", () => {
  describe("schema existence + JSON Schema validity", () => {
    it("schemas/catalog.schema.json exists and is valid JSON-Schema 2020-12", async () => {
      expect(await fs.pathExists(SCHEMA_PATH)).toBe(true);
      const raw = await fs.readFile(SCHEMA_PATH, "utf8");
      const schema = JSON.parse(raw);
      expect(schema.$schema).toMatch(/2020-12/);
      // Required top-level keys for a JSON Schema object type
      expect(schema.type).toBe("object");
      expect(schema.properties).toBeDefined();
    });

    it("schema entry defines only the 6 durable metadata fields (no ephemeral fields)", async () => {
      const schema = JSON.parse(await fs.readFile(SCHEMA_PATH, "utf8"));
      const allowed = new Set([
        "path",
        "type",
        "size",
        "mtime",
        "content_hash",
        "indexed_at",
      ]);
      // Entry-level properties live under $defs.entry.properties (JSON Schema 2020-12 convention).
      const entryProps = schema.$defs && schema.$defs.entry && schema.$defs.entry.properties;
      expect(entryProps, "schema missing $defs.entry.properties").toBeDefined();
      const props = Object.keys(entryProps);
      for (const p of props) {
        expect(allowed.has(p), `entry field "${p}" is not in the allowed durable metadata list (brief §6 explicitly forbids ephemeral fields)`).toBe(true);
      }
      // Reverse direction: every allowed field must be present
      for (const a of allowed) {
        expect(props.includes(a), `field "${a}" missing from entry schema`).toBe(true);
      }
    });

    it("schema entry forbids ephemeral fields by name (closed additionalProperties)", async () => {
      const schema = JSON.parse(await fs.readFile(SCHEMA_PATH, "utf8"));
      expect(schema.$defs.entry.additionalProperties).toBe(false);
      expect(schema.additionalProperties).toBe(false);
    });
  });

  describe("catalog library (core/src/lib/catalog.ts)", () => {
    let tmpRoot: string;
    beforeEach(async () => {
      tmpRoot = await fs.mkdtemp(path.join(os.tmpdir(), "operatoros-test-"));
      await fs.ensureDir(path.join(tmpRoot, ".operatoros"));
    });
    afterEach(async () => {
      await fs.remove(tmpRoot);
    });

    it("writes a valid catalog file at .operatoros/index.json", async () => {
      // Create a sample workspace file
      await fs.writeFile(path.join(tmpRoot, "hello.txt"), "world");
      const { buildCatalog } = await import("../src/lib/catalog");
      const catalogPath = await buildCatalog(tmpRoot);
      expect(catalogPath).toBe(path.join(tmpRoot, ".operatoros", "index.json"));
      expect(await fs.pathExists(catalogPath)).toBe(true);
      const catalog = JSON.parse(await fs.readFile(catalogPath, "utf8"));
      expect(catalog.indexed_at).toMatch(/^\d{4}-\d{2}-\d{2}T/);
      // Entries array exists and is sorted by path
      expect(Array.isArray(catalog.entries)).toBe(true);
    });

    it("catalog entries contain only the 6 durable fields per file", async () => {
      await fs.writeFile(path.join(tmpRoot, "hello.txt"), "world");
      const { buildCatalog } = await import("../src/lib/catalog");
      await buildCatalog(tmpRoot);
      const catalog = JSON.parse(
        await fs.readFile(path.join(tmpRoot, ".operatoros", "index.json"), "utf8")
      );
      // Find hello.txt entry (or one of its expected mapped entries)
      const entry = catalog.entries.find((e: any) =>
        e.path.endsWith("hello.txt")
      );
      expect(entry).toBeDefined();
      const fields = Object.keys(entry).sort();
      expect(fields).toEqual(
        ["content_hash", "indexed_at", "mtime", "path", "size", "type"].sort()
      );
    });

    it("catalog content_hash is a SHA-256 hex digest for files", async () => {
      await fs.writeFile(path.join(tmpRoot, "hello.txt"), "world");
      const { buildCatalog } = await import("../src/lib/catalog");
      await buildCatalog(tmpRoot);
      const catalog = JSON.parse(
        await fs.readFile(path.join(tmpRoot, ".operatoros", "index.json"), "utf8")
      );
      const entry = catalog.entries.find((e: any) =>
        e.path.endsWith("hello.txt")
      );
      // SHA-256 hex = 64 chars, hex chars only
      expect(entry.content_hash).toMatch(/^[a-f0-9]{64}$/);
      // Verify independently
      const sha = crypto.createHash("sha256").update("world").digest("hex");
      expect(entry.content_hash).toBe(sha);
    });

    it("catalog excludes ephemeral/runtime directories by default", async () => {
      // Create both durable + ephemeral content
      await fs.writeFile(path.join(tmpRoot, "preserve.txt"), "yes");
      await fs.ensureDir(path.join(tmpRoot, "node_modules"));
      await fs.writeFile(path.join(tmpRoot, "node_modules", "ignore.js"), "");
      await fs.ensureDir(path.join(tmpRoot, ".git"));
      await fs.writeFile(path.join(tmpRoot, ".git", "HEAD"), "ref: refs/heads/main");
      const { buildCatalog } = await import("../src/lib/catalog");
      await buildCatalog(tmpRoot);
      const catalog = JSON.parse(
        await fs.readFile(path.join(tmpRoot, ".operatoros", "index.json"), "utf8")
      );
      const paths = catalog.entries.map((e: any) => e.path);
      expect(paths.some((p: string) => p.includes("preserve.txt"))).toBe(true);
      expect(paths.some((p: string) => p.includes("node_modules"))).toBe(false);
      expect(paths.some((p: string) => p.includes(".git"))).toBe(false);
    });

    it("readCatalog returns the catalog if fresh", async () => {
      await fs.writeFile(path.join(tmpRoot, "a.md"), "x");
      const { buildCatalog, readCatalog } = await import("../src/lib/catalog");
      await buildCatalog(tmpRoot);
      const catalog = await readCatalog(tmpRoot);
      expect(catalog).not.toBeNull();
      expect(catalog!.indexed_at).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    });

    it("readCatalog returns null when no catalog exists", async () => {
      // .operatoros exists but no catalog inside
      const { readCatalog } = await import("../src/lib/catalog");
      const catalog = await readCatalog(tmpRoot);
      expect(catalog).toBeNull();
    });

    it("readCatalog detects stale catalog when files changed since indexed_at", async () => {
      await fs.writeFile(path.join(tmpRoot, "a.md"), "x");
      const { buildCatalog, readCatalog } = await import("../src/lib/catalog");
      await buildCatalog(tmpRoot);
      // Mutate a file's mtime to AFTER indexed_at — simulate edit since index.
      const target = path.join(tmpRoot, "a.md");
      const fut = new Date(Date.now() + 60_000); // +1 minute in future
      await fs.utimes(target, fut, fut);
      const result = await readCatalog(tmpRoot);
      // readCatalog must report staleness, not silently return stale data
      expect(result).not.toBeNull();
      expect(result!.stale).toBe(true);
    });
  });
});
